name: flapjack_client_core
description: >-
  Flapjack Client Core is a Dart package for seamless Flapjack API integration,
  offering HTTP request handling, retry strategy, and robust exception
  management.
version: 1.44.0
homepage: https://www.flapjack.io/doc/
repository: >-
  https://github.com/flapjackhq/flapjacksearch-client-dart/tree/main/packages/client_core
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  dio: ^5.2.1
  web: ^1.1.1
dev_dependencies:
  lints: ">=5.0.0 <7.0.0"
  test: ^1.25.8
