name: flapjacksearch
version: 1.44.0
description: A Dart package for Flapjack. Enables seamless integration for instant search, typo tolerance & user insights, and more, in Dart/Flutter apps.
homepage: https://www.flapjack.io/doc/
repository: https://github.com/flapjackhq/flapjacksearch-client-dart/tree/main/packages/flapjacksearch
topics:
  - search
  - discovery

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flapjack_client_core: ^1.44.0
  flapjack_client_search: ^1.44.0
  flapjack_client_insights: ^1.44.0
  json_annotation: ^4.8.1
  collection: ^1.17.1

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: '>=6.0.0 <6.9.0'
  lints: ">=5.0.0 <7.0.0"
  logging: ^1.2.0
  test: ^1.25.8
dependency_overrides:
  flapjack_client_core:
    path: ../client_core
  flapjack_client_search:
    path: ../client_search
  flapjack_client_insights:
    path: ../client_insights
